### ISSUE TITLE
Feedback - Week 4 Assignment

### ISSUE THREAD

**Issue by ntuvera** [rparker24/week-4-game#1]
Hey @rparker24, what's up?  I cloned your repo and tried out your game...

Nice work.  Functionality is all there and nothing is breaking.  Always a good sign :)  

In terms of your code, it's all clear and concise.  Can you tell me why you put your `reset()` and `numAdd` inside your `$(document).ready()`?  Message me here or on Slack.

Overall, great job.  If anything you might want to add some responsive styling later, if you plan to use it as a portfolio piece.

**Comment by rparker24** [comment]
Moved the functions outside of document.ready() as that didn't really make sense.
